import { Providers } from "@/components";
import "./globals.css";

export const metadata = {
  title: {
    template: "%s  - Nineties Grove",
    default: 'Nineties Grove'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
