import "./globals.css";
import { titleFont } from '@/config/fonts'

export const metadata = {
  title: "Nineties Grove",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={titleFont.className}>{children}</body>
    </html>
  );
}
